// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"透明色を考慮":"OFF","ピクチャ番号の変数番号":"0"}},
{"name":"TMBtnPicture","status":true,"description":"ピクチャをタップ（クリック）でコモンイベントを起動します。","parameters":{}},
{"name":"AltMenuScreen","status":false,"description":"メニュー画面のレイアウトを変更します。","parameters":{}},
{"name":"Yami_SkipTitle","status":false,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"AnimVar","status":true,"description":"指定変数のイベントIDに指定変数のアニメーションを起動","parameters":{}},
{"name":"ShiftEventPosition","status":true,"description":"イベントの表示位置を調整します","parameters":{}}
];
